[package]
license = ["Apache-2.0"]
keywords = ["ebay", "logistics", "shipment", "shipping_quote", "ecommerce"]
org = "ballerinax"
name = "ebay.logistics"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
