[package]
license = ["Apache-2.0"]
keywords = ["NYTimes", "Movie", "Reviews", "media", "open_data"]
org = "ballerinax"
name = "nytimes.moviereviews"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
