[package]
org = "testingopenapis"
name = "shortcut"
icon = "icon.png"
version = "1.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Project Management","Cost/Freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
