[package]
license = ["Apache-2.0"]
keywords = ["Internet of Things/Device Management", "Cost/Paid"]
org = "testingopenapis"
name = "siemens.iotandstorage.iotfileservice"
icon = "icon.png"
distribution = "slbeta3"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
