[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid"]
org = "testingopenapis"
name = "zuora.revenue"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
