[package]
distribution = "2201.0.0-20220104-134500-fb864d9d"
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.datacatalog"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
