[package]
license = ["Apache-2.0"]
keywords = ["Education/Elearning", "Cost/Paid"]
org = "testingopenapis"
name = "clever.data"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
