[package]
license = ["Apache-2.0"]
keywords = ["Apptigent", "Powertools", "Developer", "developer_tools", "text"]
org = "ballerinax"
name = "powertoolsdeveloper.text"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
