[package]
license = ["Apache-2.0"]
keywords = ["ebay", "listing", "ecommerce"]
org = "ballerinax"
name = "ebay.listing"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
