[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRM", "Cost/Paid"]
org = "testingopenapis"
name = "workday.compensation"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
