[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Paid"]
org = "testingopenapis"
name = "godaddy.certificates"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
