[package]
license = ["Apache-2.0"]
keywords = ["Support/Customer Support", "Cost/Paid"]
org = "testingopenapis"
name = "atspoke"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
