[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
org = "testingopenapis"
name = "bitbucket"
icon = "icon.png"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
