[package]
org = "testingopenapis"
name = "karbon"
icon = "icon.png"
version = "1.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Product Management","Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
