[package]
license = ["Apache-2.0"]
keywords = ["Finance/Payment", "Cost/Freemium"]
org = "testingopenapis"
name = "stripe"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.3"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
