[package]
license = ["Apache-2.0"]
keywords = ["Education/Dictionary", "Cost/Freemium"]
org = "testingopenapis"
name = "wordnik"
icon = "icon.png"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
