[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Artificial Intelligence", "Cost/Freemium", "Vendor/Google"]
org = "testingopenapis"
name = "googleapis.vision"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
