[package]
license = ["Apache-2.0"]
keywords = ["figshare", "article", "author"]
org = "ballerinax"
name = "figshare"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
