[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Free"]
org = "testingopenapis"
name = "ip2whois"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
