[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Project Management", "Cost/Paid"]
org = "testingopenapis"
name = "xero.projects"
icon = "icon.png"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
