[package]
license = ["Apache-2.0"]
keywords = ["Finance/Payment", "Cost/Freemium"]
org = "testingopenapis"
name = "paypal.orders"
icon = "icon.png"
distribution = "slbeta3"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
