
[package]
org = "ballerinax"
name = "documentum"
version = "0.1.0-SNAPSHOT"
distribution = "slbeta3"
license = ["Apache-2.0"]
keywords = ["content & files/documents", "cost/freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
