[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Paid", "Vendor/Microsoft"]
org = "testingopenapis"
name = "power.bi"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
