[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Email Newsletters", "Cost/Freemium"]
org = "testingopenapis"
name = "mailchimp"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
