[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Task Management", "Cost/Freeemium"]
org = "testingopenapis"
name = "trello"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
